### ISSUE TITLE
Performance improvements?

### ISSUE THREAD

**Issue by Kranzes** [Foxboron/age-plugin-tpm#19]
Decrypting a 1 line text file with this plugins takes about 2 seconds, is this expected?

**Comment by Foxboron** [comment]
Partially?

This depends solely on the performance of your TPM, there is nothing resource intensive happening in the go code itself.

**Comment by Kranzes** [comment]
Interesting, that's pretty damn slow then...

**Comment by Foxboron** [comment]
It doesn't have a particularly fast CPU, no.

Unless you attach some profiling or tracing of the go binary (with symbols), I'll close this as non-actionable.

**Comment by Kranzes** [comment]
Yeah I don't have the energy for that, thanks anyway.
