### ISSUE TITLE
Save the key context outside of the TPM

### ISSUE THREAD

**Issue by Foxboron** [Foxboron/age-plugin-tpm#4]
Since TPM keys are deterministic we can actually save the key context outside of the TPM isntead of a persistent handle. This saves resources on the limited hardware with the downside that the host is storing a blob.

Would need to use `tpm2.ContextSave` instead of `tpm2.EvictControl` without key handle. Then we need to use `tpm2.ContextLoad` before using the key again.

**Comment by grawity** [comment]
Hm, AFAIK, I don't think you need to save the _context_ at all –  as long as you have the SRK stored at 0x81000001 (or as long as you deterministically re-create it, which is fast enough with ECC), it should be enough to save just the `pub` and `priv` blobs that `CreateKey()` returns, which can then be `Load()`-ed later.

Only primary objects (e.g. the SRK) are deterministic, while regular keys are randomly generated – their "priv" blobs from CreateKey() are returned encrypted with their parent key, then decrypted when you Load() them back into the TPM.

**Comment by Foxboron** [comment]
This has been implemented with https://github.com/Foxboron/age-plugin-tpm/commit/2143ca1e5e282dcf1ff32a7327c9faf4c220c7b2

And then later reimplemented with the new `go-tpm` API here: https://github.com/Foxboron/age-plugin-tpm/commit/d8a916dd024ccaa725118250427ca18097abf18a
