### ISSUE TITLE
Is matrix ?

### ISSUE THREAD

**Issue by gedw99** [Foxboron/age-plugin-tpm#7]
Hey @Foxboron 

want to use this on windows.  Mac and Linux.

Any ideas what OS types are supported ?  You’re using Google’s tpm package I see .

also planning to build a basic gui with basic query capabilities with gioui

**Comment by gedw99** [comment]
Go-TPM is a Go library that communicates directly with a TPM device on Linux or Windows machines.

So I need to try on Darwin as I think the api is radically different on Darwin

**Comment by Foxboron** [comment]
OSX does not use TPMs, they use "Secure Enclave" so that needs this https://github.com/remko/age-plugin-se

I can't guarantee any functionality at this moment as the Google TPM library is getting a new API soon'ish and I'm in the progress of figuring it out.

**Comment by Foxboron** [comment]
and fwiw, I'm in the process of rewriting the identity handling so we can have TPM keys sealed outside of the TPMs to mitigate the generally small storage space the TPMs has for internal keys.

**Comment by gedw99** [comment]
Hey 

thanks for quickly responding.

right - yep apple goes their own way.. 

you know way more about it than me.

so when can I dog food it - I can help test and code it

**Comment by Foxboron** [comment]
You can play around with the tooling using the `--swtpm` flag or `AGE_PLUGIN_TPM_SWTPM=1` environment variable to utilize a software TPM (depends on `swtpm`), which would allow you to use it outside of your actual TPM.

But keep in mind I don't make any stability guarantees until an eventual 1.0 release.

**Comment by gedw99** [comment]
No sweat - it’s beta beta .

I will yt it out with the mocking layer you suggested.

**Comment by gedw99** [comment]
I had a play..

https://github.com/remko/age-plugin-se 
does not work on my old intel mac :)

But i noticed that this code can easily be turned into golang code so users don't need the brew aspects:
https://github.com/remko/age-plugin-se/tree/main/Sources

This shows the pattern for Mac
https://github.com/gioui/gio-x/blob/main/explorer/explorer_macos.go

Might be worth doing some time...

**Comment by Foxboron** [comment]
As explained over email, this plugin won't support Microsoft Windows and Apple.
