### ISSUE TITLE
Encrypting with multiple recipients results in an error upon decryption

### ISSUE THREAD

**Issue by vikanezrimaya** [Foxboron/age-plugin-tpm#8]
Test case:

```console
# Generate a key inside of a TPM
$ age-plugin-tpm -g > age-tpm.txt

# Generate a 1KB plaintext and encrypt it
$ dd if=/dev/urandom bs=1024 count=1 | age -a -r "$(age-plugin-tpm -l | tail -n1)" > test.txt.age
1+0 records in
1+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 4.4513e-05 s, 23.0 MB/s

# Try decrypting it
$ cat test.txt.age | age -d -i age-tpm.txt | wc -c
1024

# Generate another 1KB plaintext and try to encrypt it to multiple keys
$ dd if=/dev/urandom bs=1024 count=1 | age -a -r "$(age-plugin-tpm -l | tail -n1)" -r "$(age-keygen 2>/dev/null | age-keygen -y)" > test.txt.age
1+0 records in
1+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 4.2366e-05 s, 24.2 MB/s

# Try to decrypt it... wait, what?!
$ cat test.txt.age | age -d -i age-tpm.txt
age: error: tpm plugin: failed to read line: EOF
age: report unexpected or unhelpful errors at https://filippo.io/age/report

# `rage` also fails:
$ cat test.txt.age | rage -d -i age-tpm.txt
Error: incomplete response

[ Did rage not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/rage/report                            ]

# Interestingly, if a file is encrypted with rage, it is unable to be decrypted at all:
$ dd if=/dev/urandom bs=1024 count=1 | rage -a -r "$(age-plugin-tpm -l | tail -n1)" > test.txt.age
1+0 records in
1+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 4.4326e-05 s, 23.1 MB/s

$ cat test.txt.age | age -d -i age-tpm.txt
age: error: tpm plugin: failed to read line: EOF
age: report unexpected or unhelpful errors at https://filippo.io/age/report

$ cat test.txt.age | rage -d -i age-tpm.txt
Error: incomplete response

[ Did rage not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/rage/report                            ]
```

Note that in case of multiple keys encrypting a message, other keys decrypt the message successfully, no matter what it's encrypted with.

**Comment by vikanezrimaya** [comment]
Just confirmed it works with `--swtpm` flag too.

**Comment by Foxboron** [comment]
Yo, thanks for the bug report.

Multiple recipients is not implemented properly. This is mostly due to lazyness on my end as upstream don't provide proper abstractions for parsing this, and I'm mostly focusing on the TPM backend implementation.

I'll revisit this project once Google stabilizes their new TPM library, which is soon'ish.

**Comment by vikanezrimaya** [comment]
Oh, that's sad. I wanted to actually use this because I'm gonna recommend age encryption at my workplace, and I wanted to bind a key to my work laptop; but I guess I'll have to stick with a different type of key for the time being. But I don't want to abandon all hope of storing it in a TPM someday 😝

**Comment by Foxboron** [comment]
Some support for multiple recipients have been implemented in https://github.com/Foxboron/age-plugin-tpm/pull/9

Feel free to take a look, but keep in mind that the TPM keys are now rewritten to be sealed outside of the TPM instead of occupying memory inside the TPM.

**Comment by vikanezrimaya** [comment]
Compiled from 7c1ed7f787e2ce325ddbbf0261f3e54d73b63eba (#9). Doesn't look like it works:

```console
$ age-plugin-tpm --generate > ~/age-tpm.txt
$ less ~/age-tpm.txt
<A key, notably longer than the previous keys produced by this module — evidence that the key is in fact now sealed outside of the TPM>

# Try to encrypt normally
$ dd if=/dev/urandom bs=1 count=1024 | age -a -e -r $(age-plugin-tpm -y age-tpm.txt) | age -d -i ~/age-tpm.txt | wc -c
1024+0 records in
1024+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 0.000535527 s, 1.9 MB/s
1024

# Try the same thing with rage
$ dd if=/dev/urandom bs=1 count=1024 | rage -a -e -r $(age-plugin-tpm -y ~/age-tpm.txt) | age -d -i ~/age-tpm.txt | wc -c
1024+0 records in
1024+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 0.000518174 s, 2.0 MB/s
age: error: tpm plugin: parsing age header: malformed body line "ZmFpbGVkIGJhc2U2NCBkZWNvZGUgc2Vzc2lvbiBrZXk6IGlsbGVnYWwgYmFzZTY0IGRhdGEgYXQgaW5wdXQgYnl0ZSAx\n": too long
age: report unexpected or unhelpful errors at https://filippo.io/age/report
0

# Try multiple recipients with age
$ age-keygen > ~/age-key.txt
$ dd if=/dev/urandom bs=1 count=1024 | age -a -e -r $(age-plugin-tpm -y age-tpm.txt) -r $(age-keygen -y age-key.txt) | age -d -i ~/age-tpm.txt | wc -c
1024+0 records in
1024+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 0.000504025 s, 2.0 MB/s
age: error: tpm plugin: failed to read line: EOF
age: report unexpected or unhelpful errors at https://filippo.io/age/report
0

# Try to decrypt with a different recipient — works!
$ dd if=/dev/urandom bs=1 count=1024 | age -a -e -r $(age-plugin-tpm -y age-tpm.txt) -r $(age-keygen -y age-key.txt) | age -d -i ~/age-key.txt | wc -c
1024+0 records in
1024+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 0.0010784 s, 950 kB/s
1024
```

**Comment by Foxboron** [comment]
Fixed in https://github.com/Foxboron/age-plugin-tpm/pull/9/commits/0306eee86f85e12adc2b8a9c64c99528c9928f54 I think, but I'm not sure if I'll focus on fixing issues with `rage` just yet.

**Comment by Foxboron** [comment]
Okay, it seems like `rage` just works now. So unsure what the issue was there.

**Comment by vikanezrimaya** [comment]
Can confirm that it's working now. Thank you! Closing.

**Comment by Foxboron** [comment]
Thanks for testing :)

**Comment by sylvorg** [comment]
Hello! Apologies for necroposting, but this still seems to be happening to me on NixOS using agenix and ragenix. Does decryption require or rely on any services or programs I might have missed in the systemd-service?

**Comment by Foxboron** [comment]
> Apologies for necroposting, but this still seems to be happening to me on NixOS using agenix and ragenix.

Please provide detailed information on what you are seeing.

> Does decryption require or rely on any services or programs I might have missed in the systemd-service?

It doesn't.

**Comment by sylvorg** [comment]
At the moment, while agenix is attempting to decrypt the user secrets, I'm getting the following error:
```
age: error: tpm plugin: failed to read line: EOF
age: report unexpected or unhelpful errors at https://filippo.io/age/report
```
After a few tests I suspect it's because the identity does not match any of the recipients used to encrypt the secret, but if that's the case, I'm confused as to why this message would occur instead of the usual error for no recipients.

**Comment by Foxboron** [comment]
> After a few tests I suspect it's because the identity does not match any of the recipients used to encrypt the secret, but if that's the case, I'm confused as to why this message would occur instead of the usual error for no recipients.

I suspect this is more likely. If you can create a re-production of what you are seeing, please open a new issue. Else I'll try and remember this when I get back to working on `age-plugin-tpm`.

**Comment by sylvorg** [comment]
Will do. I'll see if the same error comes up outside of the agenix service when there are no matching recipients.

**Comment by sylvorg** [comment]
Okay, it seems that even though the the secret can now be decrypted by the TPM identity, it still cannot be decrypted by the agenix user service, with the same error as last time:
```
age: error: tpm plugin: failed to read line: EOF
age: report unexpected or unhelpful errors at https://filippo.io/age/report
```

**Comment by sylvorg** [comment]
Interesting... It looks like my issue is that of a non-descriptive error, in that the plugin wasn't telling me the actual problem. Adding `tss` to the supplemental groups and giving the systemd service read, write, and mount access to the tpm solved the problem. Should I open a new issue to make the error message clearer?

**Comment by Foxboron** [comment]
> Should I open a new issue to make the error message clearer?

Yes please, there is probably a permission denied error that does not get reported correctly
